-- MySQL Script generated by MySQL Workbench
-- Sat May 13 18:47:23 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tcshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tcshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tcshop` DEFAULT CHARACTER SET utf8 ;
USE `tcshop` ;

-- -----------------------------------------------------
-- Table `tcshop`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NULL,
  `login_name` VARCHAR(45) NULL,
  `register_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `password` VARCHAR(50) NULL,
  `salt` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `permission` VARCHAR(45) NOT NULL,
  `type` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`custormer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`custormer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `weixin` VARCHAR(45) NULL,
  `user_name` VARCHAR(45) NULL,
  `mobile` VARCHAR(45) NULL,
  `password` VARCHAR(50) NULL,
  `salt` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`brand` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `logo` VARCHAR(45) NULL,
  `position` INT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand_id` INT NOT NULL,
  `type` CHAR(1) NULL COMMENT '商品类型：\n1.实物商品\n2.虚拟商品',
  `code` VARCHAR(45) NULL COMMENT '商品编码',
  `name` VARCHAR(45) NULL,
  `pics` VARCHAR(512) NULL,
  `tags` VARCHAR(45) NULL,
  `price` BIGINT(11) NULL,
  `stock` INT NULL,
  `description` LONGTEXT NULL,
  `freightage` BIGINT(11) NULL COMMENT '运费',
  PRIMARY KEY (`id`, `brand_id`),
  INDEX `fk_product_brand1_idx` (`brand_id` ASC),
  CONSTRAINT `fk_product_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `tcshop`.`brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NULL,
  `name` VARCHAR(45) NULL,
  `position` INT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `custormer_id` INT NOT NULL,
  `amount` BIGINT(11) NULL COMMENT '订单总计',
  `discount` BIGINT(11) NULL COMMENT '优惠金额',
  `actual_amount` BIGINT(11) NULL COMMENT '实际金额',
  `sku_num` INT NULL COMMENT '商品总数',
  `code` VARCHAR(45) NULL COMMENT '订单编号',
  `freightage` BIGINT(11) NULL COMMENT '物流费',
  PRIMARY KEY (`id`, `custormer_id`),
  INDEX `fk_orders_custormer1_idx` (`custormer_id` ASC),
  CONSTRAINT `fk_orders_custormer1`
    FOREIGN KEY (`custormer_id`)
    REFERENCES `tcshop`.`custormer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`product_sku`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`product_sku` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `name` VARCHAR(45) NULL COMMENT '规格名',
  `price` BIGINT(11) NULL,
  `stock` INT NULL,
  PRIMARY KEY (`id`, `product_id`),
  INDEX `fk_product_sku_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_sku_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `tcshop`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`order_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orders_id` INT NOT NULL,
  `product_sku_id` INT NOT NULL,
  `num` INT NULL,
  `amount` BIGINT(11) NULL,
  PRIMARY KEY (`id`, `orders_id`, `product_sku_id`),
  INDEX `fk_order_detail_orders1_idx` (`orders_id` ASC),
  INDEX `fk_order_detail_product_sku1_idx` (`product_sku_id` ASC),
  CONSTRAINT `fk_order_detail_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `tcshop`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_detail_product_sku1`
    FOREIGN KEY (`product_sku_id`)
    REFERENCES `tcshop`.`product_sku` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`user_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`user_permission` (
  `user_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `permission_id`),
  INDEX `fk_user_has_permission_permission1_idx` (`permission_id` ASC),
  INDEX `fk_user_has_permission_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_permission_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tcshop`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_permission_permission1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `tcshop`.`permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`role_permission` (
  `role_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`role_id`, `permission_id`),
  INDEX `fk_role_has_permission_permission1_idx` (`permission_id` ASC),
  INDEX `fk_role_has_permission_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_role_has_permission_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `tcshop`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_permission_permission1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `tcshop`.`permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`user_role` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_user_has_role_role1_idx` (`role_id` ASC),
  INDEX `fk_user_has_role_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_role_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tcshop`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `tcshop`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`shop_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`shop_config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `logo` VARCHAR(45) NULL,
  `link_man` VARCHAR(45) NULL,
  `link_mobile` VARCHAR(16) NULL,
  `address` VARCHAR(45) NULL,
  `description` NVARCHAR(300) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `wx_oid` VARCHAR(45) NULL COMMENT '公众号原始ID',
  `wx_appid` VARCHAR(45) NULL COMMENT '公众号APPID',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`custorm_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`custorm_account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `balance` BIGINT(11) NULL,
  `custormer_id` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `custormer_id`),
  INDEX `fk_custorm_account_custormer1_idx` (`custormer_id` ASC),
  CONSTRAINT `fk_custorm_account_custormer1`
    FOREIGN KEY (`custormer_id`)
    REFERENCES `tcshop`.`custormer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`shop_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`shop_account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shop_config_id` INT NOT NULL,
  `balance` BIGINT(11) NULL,
  PRIMARY KEY (`id`, `shop_config_id`),
  INDEX `fk_shop_account_shop_config1_idx` (`shop_config_id` ASC),
  CONSTRAINT `fk_shop_account_shop_config1`
    FOREIGN KEY (`shop_config_id`)
    REFERENCES `tcshop`.`shop_config` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`category_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`category_product` (
  `category_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`category_id`, `product_id`),
  INDEX `fk_category_has_product_product1_idx` (`product_id` ASC),
  INDEX `fk_category_has_product_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_category_has_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `tcshop`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `tcshop`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` LONGTEXT NULL,
  `comment_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `custormer_id` INT NOT NULL,
  `orders_id` INT NOT NULL,
  PRIMARY KEY (`id`, `custormer_id`, `orders_id`),
  INDEX `fk_comment_custormer1_idx` (`custormer_id` ASC),
  INDEX `fk_comment_orders1_idx` (`orders_id` ASC),
  CONSTRAINT `fk_comment_custormer1`
    FOREIGN KEY (`custormer_id`)
    REFERENCES `tcshop`.`custormer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `tcshop`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`cart` (
  `id` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `custormer_id` INT NOT NULL,
  `product_sku_id` INT NOT NULL,
  `num` INT NULL COMMENT '商品数量',
  PRIMARY KEY (`id`, `custormer_id`, `product_sku_id`),
  INDEX `fk_cart_custormer1_idx` (`custormer_id` ASC),
  INDEX `fk_cart_product_sku1_idx` (`product_sku_id` ASC),
  CONSTRAINT `fk_cart_custormer1`
    FOREIGN KEY (`custormer_id`)
    REFERENCES `tcshop`.`custormer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_product_sku1`
    FOREIGN KEY (`product_sku_id`)
    REFERENCES `tcshop`.`product_sku` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`journal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`journal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `objecttype` CHAR(1) NULL COMMENT '交易对象类型：0，店铺；1，会员；',
  `objectid` INT NULL COMMENT '交易对象（店铺编码，店铺用户账号），0表示平台',
  `details` TEXT NULL COMMENT '交易详情',
  `journaltime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '交易时间',
  `journalmoney` BIGINT(11) NULL COMMENT '交易金额，如果为服务则为总工时费+总商品费用（含运费）（单位分）',
  `tradetype` CHAR(1) NULL DEFAULT '0' COMMENT '交易类型 0：订单；1：退款；2：充值；3：提现；4：满赠；5：平台佣金',
  `paytype` CHAR(1) NULL DEFAULT '0' COMMENT '支付方式 0：储值卡；1:现金或银行卡；2：支付宝；3：微信支付；4：优惠券',
  `journaltype` CHAR(1) NULL DEFAULT '0' COMMENT '流水类别 0：收入；1：支出；2：预收；3：赠送待定',
  `dealstatus` CHAR(1) NULL DEFAULT '0' COMMENT '交易状态 0：交易成功；1：交易失败',
  `userbalance` BIGINT(11) NULL COMMENT '当前交易后用户账户余额（冗余，否则要做统计。当前custormrid不为空时此字段必填）',
  `credentialsid` INT NULL COMMENT '凭证id（订单id,充值记录id）',
  `credentialstype` CHAR(1) NULL COMMENT '凭证类型：0，订单；1，充值',
  `shopid` INT NULL COMMENT 'objecttype=0时使用 店铺ID',
  `custormerid` INT NULL COMMENT 'objecttype=1时使用 会员ID',
  `user` NVARCHAR(50) NULL COMMENT '制单人名字(id:名称)',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`refund`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`refund` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orders_id` INT NOT NULL,
  `custormer_id` INT NOT NULL,
  `reason` NVARCHAR(200) NULL COMMENT '原因',
  `code` VARCHAR(45) NULL COMMENT '维权申请编号',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `type` CHAR(1) NULL COMMENT '处理方式\n1.退款\n2.补货\n3.退货退款',
  `mobile` VARCHAR(16) NULL COMMENT '联系电话',
  `order_detail_id` INT NOT NULL,
  `status` CHAR(1) NULL COMMENT '申请状态\n1.同意\n2.拒绝',
  PRIMARY KEY (`id`, `orders_id`, `custormer_id`, `order_detail_id`),
  INDEX `fk_refund_orders1_idx` (`orders_id` ASC),
  INDEX `fk_refund_custormer1_idx` (`custormer_id` ASC),
  INDEX `fk_refund_order_detail1_idx` (`order_detail_id` ASC),
  CONSTRAINT `fk_refund_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `tcshop`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_refund_custormer1`
    FOREIGN KEY (`custormer_id`)
    REFERENCES `tcshop`.`custormer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_refund_order_detail1`
    FOREIGN KEY (`order_detail_id`)
    REFERENCES `tcshop`.`order_detail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`favorite` (
  `custormer_id` INT NOT NULL,
  `product_sku_id` INT NOT NULL,
  PRIMARY KEY (`custormer_id`, `product_sku_id`),
  INDEX `fk_custormer_has_product_sku_product_sku1_idx` (`product_sku_id` ASC),
  INDEX `fk_custormer_has_product_sku_custormer1_idx` (`custormer_id` ASC),
  CONSTRAINT `fk_custormer_has_product_sku_custormer1`
    FOREIGN KEY (`custormer_id`)
    REFERENCES `tcshop`.`custormer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_custormer_has_product_sku_product_sku1`
    FOREIGN KEY (`product_sku_id`)
    REFERENCES `tcshop`.`product_sku` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`order_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`order_logs` (
  `orders_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `content` NVARCHAR(500) NULL COMMENT '日志内容',
  PRIMARY KEY (`orders_id`, `user_id`),
  INDEX `fk_orders_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_orders_has_user_orders1_idx` (`orders_id` ASC),
  CONSTRAINT `fk_orders_has_user_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `tcshop`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tcshop`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`wxpay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`wxpay` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shop_config_id` INT NOT NULL,
  `type` CHAR(1) NULL COMMENT '支付方式：\n1.扫码支付\n2.公众号支付',
  `appid` VARCHAR(45) NULL,
  `callback_url` VARCHAR(45) NULL COMMENT '支付回调地址',
  `apikey` VARCHAR(32) NULL COMMENT 'api密钥',
  `vendor_id` VARCHAR(45) NULL COMMENT '商户号',
  `vendor_cert` VARCHAR(45) NULL COMMENT '商户证书',
  PRIMARY KEY (`id`, `shop_config_id`),
  INDEX `fk_wxpay_shop_config1_idx` (`shop_config_id` ASC),
  CONSTRAINT `fk_wxpay_shop_config1`
    FOREIGN KEY (`shop_config_id`)
    REFERENCES `tcshop`.`shop_config` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`media` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `origin_link` VARCHAR(45) NULL,
  `pic` VARCHAR(45) NULL,
  `summary` NVARCHAR(200) NULL,
  `content` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`wx_replay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`wx_replay` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL COMMENT '回复规则名',
  `event` CHAR(1) NULL COMMENT '触发事件\n1.自动回复\n2.关注回复',
  `keywords` VARCHAR(45) NULL COMMENT '关键字',
  `re_type` CHAR(1) NULL COMMENT '回复类型\n1.文本消息\n2.图文消息',
  `content` LONGTEXT NULL,
  `shop_config_id` INT NOT NULL,
  `media_id` INT NOT NULL,
  PRIMARY KEY (`id`, `shop_config_id`, `media_id`),
  INDEX `fk_wx_replay_shop_config1_idx` (`shop_config_id` ASC),
  INDEX `fk_wx_replay_media1_idx` (`media_id` ASC),
  CONSTRAINT `fk_wx_replay_shop_config1`
    FOREIGN KEY (`shop_config_id`)
    REFERENCES `tcshop`.`shop_config` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wx_replay_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `tcshop`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`wx_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`wx_menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `parent_id` INT NOT NULL,
  `act_type` CHAR(1) NULL COMMENT '菜单动作\n1.跳转链接\n2.发送消息',
  `content` LONGTEXT NULL,
  `link_url` VARCHAR(45) NULL,
  `shop_config_id` INT NOT NULL,
  `media_id` INT NOT NULL,
  PRIMARY KEY (`id`, `parent_id`, `shop_config_id`, `media_id`),
  INDEX `fk_wx_menu_wx_menu1_idx` (`parent_id` ASC),
  INDEX `fk_wx_menu_shop_config1_idx` (`shop_config_id` ASC),
  INDEX `fk_wx_menu_media1_idx` (`media_id` ASC),
  CONSTRAINT `fk_wx_menu_wx_menu1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `tcshop`.`wx_menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wx_menu_shop_config1`
    FOREIGN KEY (`shop_config_id`)
    REFERENCES `tcshop`.`shop_config` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wx_menu_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `tcshop`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcshop`.`refund_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcshop`.`refund_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(200) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `refund_id` INT NOT NULL,
  PRIMARY KEY (`id`, `refund_id`),
  INDEX `fk_refund_log_refund1_idx` (`refund_id` ASC),
  CONSTRAINT `fk_refund_log_refund1`
    FOREIGN KEY (`refund_id`)
    REFERENCES `tcshop`.`refund` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
